name: Deploy to Production

on:
  push:
    branches:
      - refresh-2024

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4" # Adjust the PHP version as needed

      - name: Add HTTP basic auth credentials for ACF
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Install SSH Host Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          name: github-actions
          known_hosts: ${{ secrets.HOST_KEY }}
          config: |
            host ssh-eikon.alwaysdata.net
            IdentityFile ~/.ssh/github-actions
            IdentitiesOnly yes
            ForwardAgent yes

      - name: Install SSH Key
        run: |
          eval "$(ssh-agent -s)"
          ssh-add -D
          ssh-add ~/.ssh/github-actions

      - name: Set SSH Key Permissions
        run: chmod 600 ~/.ssh/github-actions

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Adjust the Node.js version as needed

      - name: Install NPM dependencies for blocks
        run: |
          cd web/app/mu-plugins
          for dir in eikonblocks-*; do
            if [ -d "$dir" ] && [ -f "$dir/package.json" ]; then
              echo "Installing dependencies in $dir"
              cd "$dir"
              npm ci
              npm run build
              cd ..
            fi
          done

      - name: Sync files to server
        run: rsync -avz --delete --exclude '.env' --exclude 'web/.htaccess' -e "ssh -o BatchMode=yes" ./ eikon@ssh-eikon.alwaysdata.net:/home/eikon/www/inside-2024.eikon.ch/current
        env:
          RSYNC_RSH: "ssh -o BatchMode=yes -o StrictHostKeyChecking=no"

      - name: Set up environment
        run: |
          ssh eikon@ssh-eikon.alwaysdata.net "if [ -L /home/eikon/www/inside-2024.eikon.ch/current/.env ]; then rm /home/eikon/www/inside-2024.eikon.ch/current/.env; fi"
          ssh eikon@ssh-eikon.alwaysdata.net "ln -s /home/eikon/www/inside-2024.eikon.ch/shared/.env /home/eikon/www/inside-2024.eikon.ch/current/.env"
          ssh eikon@ssh-eikon.alwaysdata.net "if [ -L /home/eikon/www/inside-2024.eikon.ch/current/web/.htaccess ]; then rm /home/eikon/www/inside-2024.eikon.ch/current/web/.htaccess; fi"
          ssh eikon@ssh-eikon.alwaysdata.net "ln -s /home/eikon/www/inside-2024.eikon.ch/shared/web/.htaccess /home/eikon/www/inside-2024.eikon.ch/current/web/.htaccess"
          ssh eikon@ssh-eikon.alwaysdata.net "if [ -L /home/eikon/www/inside-2024.eikon.ch/current/web/app/uploads ]; then rm /home/eikon/www/inside-2024.eikon.ch/current/web/app/uploads; fi"
          ssh eikon@ssh-eikon.alwaysdata.net "ln -s /home/eikon/www/inside.eikon.ch/shared/web/app/uploads /home/eikon/www/inside-2024.eikon.ch/current/web/app"

      - name: Clear opcache
        run: |
          ssh eikon@ssh-eikon.alwaysdata.net "echo '<?php opcache_reset(); ?>' > /home/eikon/www/inside-2024.eikon.ch/current/web/opcache_clear.php"
          ssh eikon@ssh-eikon.alwaysdata.net "curl -s https://inside-2024.eikon.ch/opcache_clear.php"
          ssh eikon@ssh-eikon.alwaysdata.net "rm -rf /home/eikon/www/inside-2024.eikon.ch/current/web/opcache_clear.php"
