name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # Adjust the PHP version as needed

      - name: Add HTTP basic auth credentials for ACF
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Install SSH Host Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          name: github-actions
          known_hosts: ${{ secrets.HOST_KEY }}
          config: |
            host ${{ vars.SSH_HOST }}
            IdentityFile ~/.ssh/github-actions
            IdentitiesOnly yes
            ForwardAgent yes

      - name: Install SSH Key
        run: |
          eval "$(ssh-agent -s)"
          ssh-add -D
          ssh-add ~/.ssh/github-actions

      - name: Set SSH Key Permissions
        run: chmod 600 ~/.ssh/github-actions

      - name: Sync files to server
        run: rsync -avz --delete --exclude '.env' --exclude 'web/.htaccess' -e "ssh -o BatchMode=yes" ./ ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:${{ vars.DEPLOY_PATH }}/current
        env:
          RSYNC_RSH: "ssh -o BatchMode=yes -o StrictHostKeyChecking=no"

      - name: Set up environment
        run: |
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "if [ -L ${{ vars.DEPLOY_PATH }}/current/.env ]; then rm ${{ vars.DEPLOY_PATH }}/current/.env; fi"
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "ln -s ${{ vars.DEPLOY_PATH }}/shared/.env ${{ vars.DEPLOY_PATH }}/current/.env"
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "if [ -L ${{ vars.DEPLOY_PATH }}/current/web/.htaccess ]; then rm ${{ vars.DEPLOY_PATH }}/current/web/.htaccess; fi"
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "ln -s ${{ vars.DEPLOY_PATH }}/shared/web/.htaccess ${{ vars.DEPLOY_PATH }}/current/web/.htaccess"
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "if [ -L ${{ vars.DEPLOY_PATH }}/current/web/app/uploads ]; then rm ${{ vars.DEPLOY_PATH }}/current/web/app/uploads; fi"
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "ln -s ${{ vars.DEPLOY_PATH }}/shared/web/app/uploads ${{ vars.DEPLOY_PATH }}/current/web/app"

      - name: Clear opcache
        run: |
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "echo '<?php opcache_reset(); ?>' > ${{ vars.DEPLOY_PATH }}/current/web/opcache_clear.php"
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "curl -s https://inside-2024.eikon.ch/opcache_clear.php"
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "rm -rf ${{ vars.DEPLOY_PATH }}/current/web/opcache_clear.php"
