name: Deploy staging with Capistrano

on:
  push:
    branches:
      - refresh-2024

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add HTTP basic auth credentials for ACF
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8
          bundler-cache: false

      - name: Install SSH Host Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          name: github-actions
          known_hosts: ${{ secrets.HOST_KEY }}
          config: |
            host ssh-eikon.alwaysdata.net
            IdentityFile ~/.ssh/github-actions
            IdentitiesOnly yes
            ForwardAgent yes

      - name: Install SSH Key
        run: |
          eval "$(ssh-agent -s)"
          ssh-add -D
          ssh-add ~/.ssh/github-actions

      - name: Check SSH Key Viability
        run: |
          ls ~/.ssh
          cat ~/.ssh/config
          ssh -o StrictHostKeyChecking=no -t eikon@ssh-eikon.alwaysdata.net "ls -al"

      - name: Remove Bundler Deployment Config
        run: bundle config --delete deployment

      - name: Install Dependencies
        run: bundle install

      - name: Deploy to staging
        run: |
          bundle exec cap staging deploy
        env:
          SSHKIT_COLOR: "1" # Enable colored output for better readability
