name: Deploy staging with Capistrano

on:
  push:
    branches:
      - refresh-2024

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add HTTP basic auth credentials for ACF
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: false # runs 'bundle install' and caches installed gems automatically

      - name: Install SSH Host Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          name: github-actions
          known_hosts: ${{ secrets.HOST_KEY }}
          config: |
            host ssh-eikon.alwaysdata.net
            IdentityFile ~/.ssh/github-actions
            IdentitiesOnly yes
            ForwardAgent yes

      - name: Install SSH Key
        run: |
          eval "$(ssh-agent -s)"
          ssh-add -D
          ssh-add ~/.ssh/github-actions

      - name: Check SSH Key Viability
        run: |
          ls ~/.ssh
          cat ~/.ssh/config
          ssh -o StrictHostKeyChecking=no -t eikon@ssh-eikon.alwaysdata.net "ls -al"

      - name: Remove Bundler Deployment Config
        run: bundle config --delete deployment

      - name: Install Dependencies
        run: bundle install

      - uses: miloserdow/capistrano-deploy@master
        with:
          target: production # Defines the environment that will be used for the deployment
          deploy_key: ${{ secrets.DEPLOY_ENC_KEY }} # Name of the variable configured in Settings/Secrets of your github project
          enc_rsa_key_pth: "deploy/deploy_id_rsa_enc"
