name: Deploy to Production

on:
  push:
    branches:
      - refresh-2024

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4" # Adjust the PHP version as needed

      - name: Add HTTP basic auth credentials for ACF
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Install SSH Host Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          name: github-actions
          known_hosts: ${{ secrets.HOST_KEY }}
          config: |
            host ssh-eikon.alwaysdata.net
            IdentityFile ~/.ssh/github-actions
            IdentitiesOnly yes
            ForwardAgent yes

      - name: Install SSH Key
        run: |
          eval "$(ssh-agent -s)"
          ssh-add -D
          ssh-add ~/.ssh/github-actions

      - name: Set SSH Key Permissions
        run: chmod 600 ~/.ssh/github-actions

      - name: Check SSH Key Viability
        run: |
          ls -la ~/.ssh
          cat ~/.ssh/config
          ssh-add -l
          ssh -o BatchMode=yes -o StrictHostKeyChecking=no eikon@ssh-eikon.alwaysdata.net "ls -al"

      - name: Sync files to server
        run: rsync -avz --delete --exclude '.env' --exclude 'web/.htaccess' -e "ssh -o BatchMode=yes -o StrictHostKeyChecking=no -o IdentitiesOnly=yes" ./ ssh-eikon.alwaysdata.net:/home/eikon/www/inside-2024.eikon.ch
